services:
  app:
    build: .
    container_name: blazor-order-app
    ports:
      - "8888:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=blazor_order_app;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: blazor-order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blazor_order_app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blazor-order-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com   # ログイン用メール
      PGADMIN_DEFAULT_PASSWORD: admin          # ログイン用パスワード
    ports:
      - "8081:80"   # ブラウザから http://localhost:8081 でアクセス
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: